/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lupita-mi-amor
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPeliculas
     */
    public ViewPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_id = new javax.swing.JLabel();
        jl_nombrepelicula = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jl_duracion = new javax.swing.JLabel();
        jl_descripcion = new javax.swing.JLabel();
        jtf_id_peliculas = new javax.swing.JTextField();
        jtf_nombrepelicula = new javax.swing.JTextField();
        jtf_duracion = new javax.swing.JTextField();
        jtf_descripcion = new javax.swing.JTextField();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_quitar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jcb_formato = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_id.setBackground(new java.awt.Color(0, 0, 0));
        jl_id.setForeground(new java.awt.Color(255, 255, 255));
        jl_id.setText("ID");
        add(jl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 39, -1, -1));

        jl_nombrepelicula.setBackground(new java.awt.Color(0, 0, 0));
        jl_nombrepelicula.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombrepelicula.setText("NOMBRE DE PELICULA");
        add(jl_nombrepelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 83, -1, -1));

        jl_formato.setBackground(new java.awt.Color(0, 0, 0));
        jl_formato.setForeground(new java.awt.Color(255, 255, 255));
        jl_formato.setText("FORMATO");
        add(jl_formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 132, -1, -1));

        jl_duracion.setBackground(new java.awt.Color(0, 0, 0));
        jl_duracion.setForeground(new java.awt.Color(255, 255, 255));
        jl_duracion.setText("DURACION");
        add(jl_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 179, -1, -1));

        jl_descripcion.setBackground(new java.awt.Color(0, 0, 0));
        jl_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        jl_descripcion.setText("DESCRIPCION");
        add(jl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 224, -1, -1));
        add(jtf_id_peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 36, 116, -1));
        add(jtf_nombrepelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 80, 116, -1));
        add(jtf_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 176, 116, -1));
        add(jtf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 221, 116, -1));

        jbtn_agregar.setText("AGREGAR");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 252, -1, -1));

        jbtn_modificar.setText("ACTUALIZAR");
        add(jbtn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 252, -1, -1));

        jbtn_quitar.setText("ELIMINAR");
        add(jbtn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 252, -1, -1));

        jbtn_nuevo.setText("NUEVO");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 7, -1, -1));

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1) - copia.png"))); // NOI18N
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido (1).png"))); // NOI18N
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido.png"))); // NOI18N
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jbtn_ultimo.setForeground(new java.awt.Color(51, 255, 255));
        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1).png"))); // NOI18N
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jcb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blu-ray" }));
        add(jcb_formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 110, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_quitar;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JComboBox<String> jcb_formato;
    public javax.swing.JLabel jl_descripcion;
    public javax.swing.JLabel jl_duracion;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_id;
    public javax.swing.JLabel jl_nombrepelicula;
    public javax.swing.JTextField jtf_descripcion;
    public javax.swing.JTextField jtf_duracion;
    public javax.swing.JTextField jtf_id_peliculas;
    public javax.swing.JTextField jtf_nombrepelicula;
    // End of variables declaration//GEN-END:variables
}
