/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lupita-mi-amor
 */
public class ViewRentas extends javax.swing.JPanel {

    /**
     * Creates new form ViewRentas
     */
    public ViewRentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_id_renta = new javax.swing.JLabel();
        jl_id = new javax.swing.JLabel();
        jl_id_peliculas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_costo_dia = new javax.swing.JLabel();
        jtf_id_rentas = new javax.swing.JTextField();
        jtf_id = new javax.swing.JTextField();
        jtf_id_peliculas = new javax.swing.JTextField();
        jcb_formato = new javax.swing.JComboBox<>();
        jl_dias = new javax.swing.JLabel();
        jl_totalrenta = new javax.swing.JLabel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_quitar = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jtf_costo_dia = new javax.swing.JTextField();
        jtf_dias = new javax.swing.JTextField();
        jtf_totalrenta = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_id_renta.setForeground(new java.awt.Color(255, 255, 255));
        jl_id_renta.setText("ID_RENTA");
        add(jl_id_renta, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 30, -1, -1));

        jl_id.setForeground(new java.awt.Color(255, 255, 255));
        jl_id.setText("ID_CLIENTES");
        add(jl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 73, -1, -1));

        jl_id_peliculas.setForeground(new java.awt.Color(255, 255, 255));
        jl_id_peliculas.setText("ID_PELICULAS");
        add(jl_id_peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 116, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORMATO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 159, -1, -1));

        jl_costo_dia.setForeground(new java.awt.Color(255, 255, 255));
        jl_costo_dia.setText("COSTO DIARIO");
        add(jl_costo_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 187, -1, -1));
        add(jtf_id_rentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 27, 105, -1));
        add(jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 70, 105, -1));
        add(jtf_id_peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 113, 105, -1));

        jcb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blu-ray" }));
        add(jcb_formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 156, 105, -1));

        jl_dias.setForeground(new java.awt.Color(255, 255, 255));
        jl_dias.setText("DIAS");
        add(jl_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jl_totalrenta.setForeground(new java.awt.Color(255, 255, 255));
        jl_totalrenta.setText("TOTAL DE RENTA");
        add(jl_totalrenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jbtn_agregar.setText("AGREGAR");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jbtn_modificar.setText("ACTUALIZAR");
        add(jbtn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jbtn_quitar.setText("ELIMINAR");
        add(jbtn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1) - copia.png"))); // NOI18N
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido (1).png"))); // NOI18N
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido.png"))); // NOI18N
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jbtn_ultimo.setForeground(new java.awt.Color(51, 255, 255));
        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1).png"))); // NOI18N
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jbtn_nuevo.setText("NUEVO");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 11, -1, -1));
        add(jtf_costo_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 187, 95, -1));
        add(jtf_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 213, 105, -1));
        add(jtf_totalrenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 251, 105, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel4;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_quitar;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JComboBox<String> jcb_formato;
    public javax.swing.JLabel jl_costo_dia;
    public javax.swing.JLabel jl_dias;
    public javax.swing.JLabel jl_id;
    public javax.swing.JLabel jl_id_peliculas;
    public javax.swing.JLabel jl_id_renta;
    public javax.swing.JLabel jl_totalrenta;
    public javax.swing.JTextField jtf_costo_dia;
    public javax.swing.JTextField jtf_dias;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_id_peliculas;
    public javax.swing.JTextField jtf_id_rentas;
    public javax.swing.JTextField jtf_totalrenta;
    // End of variables declaration//GEN-END:variables
}
