/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lupita-mi-amor
 */
public class ViewClientes extends javax.swing.JPanel {

    /**
     * Creates new form ViewClientes
     */
    public ViewClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_agregar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_quitar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jl_id = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jl_direccion = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jtf_direccion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_agregar.setText("AGREGAR");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 229, -1, -1));

        jbtn_modificar.setText("ACTUALIZAR");
        add(jbtn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 229, -1, -1));

        jbtn_quitar.setText("ELIMINAR");
        add(jbtn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 229, -1, -1));

        jbtn_nuevo.setText("NUEVO");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1) - copia.png"))); // NOI18N
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido (1).png"))); // NOI18N
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avance-rapido.png"))); // NOI18N
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/jugar (1).png"))); // NOI18N
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jl_id.setForeground(new java.awt.Color(255, 255, 255));
        jl_id.setText("ID");
        add(jl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 27, -1, -1));

        jl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombre.setText("NOMBRE");
        add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 65, -1, -1));

        jl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jl_telefono.setText("TELEFONO");
        add(jl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 103, -1, -1));

        jl_email.setForeground(new java.awt.Color(255, 255, 255));
        jl_email.setText("EMAIL");
        add(jl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 141, -1, -1));

        jl_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jl_direccion.setText("DIRECCION");
        add(jl_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 179, -1, -1));
        add(jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, -1));
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, -1));
        add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, -1));
        add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, -1));
        add(jtf_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_quitar;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_direccion;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_id;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JTextField jtf_direccion;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
